services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: always
    read_only: true
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "0.01"
          memory: 8M
        limits:
          cpus: "0.1"
          memory: 16M
    network_mode: "none"
    environment:
      - "TZ=${TZ}"
      - "AUTOHEAL_CONTAINER_LABEL=all"
      - "AUTOHEAL_START_PERIOD=300"
      - "AUTOHEAL_INTERVAL=30"
      - "AUTOHEAL_DEFAULT_STOP_TIMEOUT=10"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
